### ISSUE TITLE
[BUG] test_meta_title?

### ISSUE THREAD

**Issue by 4nh51rk** [LaravelDaily/Test-Laravel-Blade-Basics#56]
Hi @PovilasKorop 

First thanks for your time and effort in creating these Tests.

The test `public function test_meta_title()` is passing.
Just changing the line `{{ __('Dashboard') }}` to `{{ __('Blade Test') }}` in
`dashboard.blade.php`

Regards
Hari Krishna Bhagavatula

**Comment by PovilasKorop** [comment]
@4nh51rk hi, yeah, good point, probably the test should be more sophisticated, testing exactly what I had in mind, the title.

But now it's too late to change the tests cause it may invalidate the PRs that had already succeeded, so it's better be fair for everyone :)

Will be more precise for expected results in the future tests.
